package com.github.mrdroox.projects.utilities

enum class CommandCategory {
    DEVELOPER, ECONOMY, FORTNITE, FUN, GIVEAWAY, IMAGE,
    LEAGUE_OF_LEGENDS, MISCELLANEOUS, MINECRAFT, MODERATION,
    MUSIC, PREMIUM, ROBLOX, SOCIAL, UTILITIES, ZOE_ROOM
}