package com.github.mrdrooxbr.rioru.bot.commands.framework

enum class CommandCategory {
    DEVELOPER, ECONOMY, FORTNITE, FUN, GIVEAWAY, IMAGE,
    LEAGUE_OF_LEGENDS, MISCELLANEOUS, MINECRAFT, MODERATION,
    MUSIC, PREMIUM, ROBLOX, SOCIAL, UTILITIES, RIORU_ROOM, RIORU_TEAM
}